config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy]

  root 'welcomes#index'
  resources :welcomes, only: :index
  get 'about' => 'welcomes#about'
  get 'faqs' => 'welcomes#faqs'

  resources :events do
    resources :categories, only: [:show, :new, :create]
    resources :attendees, only: [:create, :destroy]
  end

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  validates :user, presence: true
  validates :event, presence: true

  belongs_to :user
  belongs_to :event
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  validates :event, presence: true
  validates :category, presence: true

  belongs_to :event
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true

  has_many :categorizations
  has_many :categories, through: :categorizations

  # def self.search(search)
  #   if search
  #     where('name ILIKE ?', "%#{search}%")
  #   else
  #     find(:all)
  #   end
  # end
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :available_seats, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :host_id, presence: true

  belongs_to :host, class_name: 'User'
  has_many  :attendees, dependent: :destroy
  # has_many  :reviews, dependent: :destroy
  has_many  :categorizations, dependent: :destroy
  has_many  :categories, through: :categorizations

  # def self.search(search)
  #   if search
  #     where('description ILIKE ?', "%#{search}%")
  #   else
  #     find(:all)
  #   end
  # end
end

app/models/user.rb
 class User < ActiveRecord::Base
  mount_uploader :profile_photo, ProfilePhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true

  has_many :events, foreign_key: 'host_id'
  has_many :attendees
  # has_many :reviews

  def is_attending?(event)
    #return true if user is an attendee
    attendee = Attendee.where(user: self, event: event).first
    if attendee
      true
    else
      false
    end
  end

  def attendee_for(event)
    Attendee.where(user: self, event: event).first
  end

  geocoded_by :full_address
  # the callback to set longitude and latitude
  after_validation :geocode

  def full_address
    [street_address, city, state, zip_code].compact.join(', ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :street_address, :city, :state, :zip_code, :about, :profile_photo]
  end

  def after_sign_in_path_for(resource)
    events_path
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :authenticate_user!

  def create
    @event = Event.find(params[:event_id])
    @attendee = Attendee.new(user: current_user, event: @event)

    if @attendee.save
      flash[:notice] = "Success! You have RSVP'd."
      redirect_to event_path(@event)
    else
      flash[:notice] = "Error"
      render "event/show"
    end
  end

  def destroy
    @event = Event.find(params[:event_id])
    @attendee = Attendee.where(event: @event).first

    if @attendee.destroy
      flash[:notice] = "Success! You have withdrawn your RSVP'd."
      redirect_to event_path(@event)
    else
      flash[:notice] = "Error"
      render "event/show"
    end
  end

  private
  def user_params
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    if current_user
      @user = current_user
      users = User.near([@user.latitude, @user.longitude], 0.25)
      user_ids = []
      users.each do |user|
        unless user.id.nil?
          user_ids << user.id
        end
      end
      @events = Event.where("host_id IN (?)", user_ids)
    else
      if params[:search].present?
        users = User.near([params[:search], 0.25])
        user_ids = []
        users.each do |user|
          unless user.id.nil?
            user_ids << user.id
          end
        end
        @events = Event.where("host_id IN (?)", user_ids)
      else
        @events = Event.all
      end
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendees = Attendee.where(event: @event)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.host = current_user

    if @event.save
      params[:event][:category_ids].each do |category_id|
        if category_id != ""
          category = Category.find(category_id)
          Categorization.create(event: @event, category: category)
        end
      end
      flash[:notice] = 'Success! Your event is live.'
      redirect_to @event
    else
      flash.now[:notice] = 'Error. Please try again.'
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
    authorize_to_edit
  end

  def update
    @event = Event.find(params[:id])
    authorize_to_edit
    if @event.update(event_params)
      flash[:notice] = 'Success'
      redirect_to event_path(@event)
    else
      flash.now[:notice] = 'Error'
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    authorize_to_edit
    if @event.destroy
      flash[:notice] = 'Deleted'
      redirect_to events_path
    else
      flash[:notice] = 'Error'
      render :show
    end
  end

  private
  def event_params
    params.require(:event).permit(:title, :description,
      :available_seats, :start_time, :end_time)
  end

  def authorize_to_edit
    if current_user != @event.host
      flash[:notice] = 'You are not authorized to do that.'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def user_params
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
    if signed_in?
      redirect_to events_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.erb
<h1>Edit Your Event</h1>
<p>* Required information</p><br/>
<%= link_to "Delete Event", event_path(@event), method: :delete, data: {:confirm => "Are you sure?"} %>

<%= simple_form_for(@event, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
  }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, required: true, autofocus: true %>
    <%= f.association :categories, :as => :check_boxes, label_method: :name, required: true %>
    <%= f.input :description, required: true %>
    <%= f.input :available_seats, required: true, label: 'Available Seats' %>
    <%= f.input :start_time, required: true, label: 'Start Time' %>
    <%= f.input :end_time, required: true, label: 'End Time' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save event edits" %>
  </div>
<% end %><br/><br/>

app/views/events/index.html.erb
<div class="events-index">
  <%- if user_signed_in? -%>
    <% content_for :body_class, "signed-in" %>
    <input type="hidden" value="<%= @user.latitude %>" id="latitude" style="display: none">
    <input type="hidden" value="<%= @user.longitude %>" id="longitude" style="display: none">

    <h1 class="appear delay-1">Events in Your Area!</h1>
    <div class="appear delay-2 events-list">
        <% @events.each do |event| %>
          <%= link_to event.title, event_path(event) %><br/>
        <% end %>
    </div>
  <%- else -%>
    <% content_for :body_class, "signed-out" %>
    <h1 class="appear delay-1">Events in Your Area!</h1>
    <div class="appear delay-2 events-list">
      <p>Sign in to see event details.</p><br/>
        <% @events.each do |event| %>
          <%= event.title %><br/>
        <% end %>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Host a new event</h1>
<p>* Required information</p><br/>

<%= simple_form_for(@event, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, required: true, autofocus: true %>
    <%= f.association :categories, :as => :check_boxes, label_method: :name, required: true %>
    <%= f.input :description, required: true %>
    <%= f.input :available_seats, required: true, label: 'Available Seats' %>
    <%= f.input :start_time, required: true, label: 'Start Time' %>
    <%= f.input :end_time, required: true, label: 'End Time' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Start hosting your event" %>
  </div>
<% end %><br/><br/>

app/views/events/show.html.erb
<div class="event-show">
  <% content_for :body_class, "signed-in" %>

  <h1><%= @event.title %></h1>
  <div class="event-details">
    <div class="event-create">
      Created by <%= link_to @event.host.first_name, user_path(@event.host) %>
      <% if @event.host == current_user %>
          (<%= link_to 'Edit event', edit_event_path(@event) %>)
      <% end %>
    </div>

    <div class="event-info">
      <strong>Categories:</strong>
      <ul>
        <% @event.categories.each do |category| %>
          <li><%= category.name %></li>
        <% end %>
      </ul>
    </div>

    <div class="event-info">
      <strong>Description:</strong><br/><%= @event.description %><br/><br/>
      <strong>Available Seats:</strong> <%= @event.available_seats %><br/><br/>
      <strong>Start Time:</strong> <%= @event.start_time.hour %>:<%= @event.start_time.min %><br/>
      <strong>End Time:</strong> <%= @event.end_time.hour %>:<%= @event.end_time.min %>
    </div>

    <div class="event-info">
      <% if @event.host != current_user %>
        <% if current_user.is_attending?(@event) %>
          <% if @event.attendees.count >= 3 %>
            Event Location:<br/>
            <%= @event.host.street_address %><br/>
            <%= @event.host.city %>, <%= @event.host.state %><br/>
            <%= @event.host.zip_code %>
          <% end %>
          <%= button_to 'Withdraw RSVP', event_attendee_path(@event, current_user.attendee_for(@event)), method: :delete %>
        <% else %>
          <%= button_to 'RSVP', event_attendees_path(@event), id: 'rsvp-button' %>
        <% end %>
      <% end %>
    </div>

    <div class="event-info">
      <strong>Current Attendees:</strong><br/>
      <ul>
        <% @attendees.each do |attendee| %>
          <li><%= attendee.user.first_name %></li><br/>
        <% end %>
      </ul>
    </div>

    <div class="event-info">
      <%= link_to 'Back to events list', events_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>WeatherBloc</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="body <%= yield (:body_class) %>">
    <div class="curtain-down"></div>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">WeatherBloc</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'About', about_path %></li>
            <%- if user_signed_in? -%>
              <li><%= link_to 'Live events', events_path %></li>
              <li><%= link_to 'Host a new event', new_event_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <%- else -%>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            <%- end -%>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container" id="main-container">
      <%= notice %>
      <%= alert %>
      <%= yield %>
    </div>

    <div class="curtain-up"></div>
  </body>
</html>

app/views/users/show.html.erb
<div class="users-show">
  <h1><%= @user.first_name %>'s Profile</h1>
  <div class="users-details">
    <div class="users-private">
      <% if @user == current_user %>
        <div class="users-info" id="users-edit">
          (<%= link_to 'Edit profile', edit_user_path(@user) %>)
        </div>
        <div class="users-info section-label" id="users-private-label">
          Personal Info (seen by only you):
        </div>
        <div class="users-info" id="users-location">
          Full Name: <%= @user.first_name %> <%= @user.last_name %><br/>
          Street Address: <%= @user.street_address %><br/>
          City: <%= @user.city %><br/>
          State: <%= @user.state %><br/>
          Zip Code: <%= @user.zip_code %>
        </div>
      <% end %>
    </div>

    <div class="users-global">
      <% if @user == current_user %>
        <div class="users-info section-label" id="users-global-label">
          Profile Info (seen by everyone):
        </div>
      <% end %>

      <div class="users-info" id="users-photo">
        <h3>Profile Photo:</h3><br/>
        <img src="<%= @user.profile_photo %>">
      </div>
      <div class="users-info" id="users-about">
        <h3>About:</h3><br/>
        <%= @user.about %><br/>
      </div>
      <div class="users-info" id="users-hosted">
        <h3>Events hosted:</h3><br/>
      </div>
    </div>
    <!-- Add back button to event page -->
  </div>
</div>

app/views/welcomes/about.html.erb
<div class="about-show">
  <h1>About</h1>
  <div class="about-details">
    <div class="about-info">
      My name is Helen and I created WeatherBloc. WeatherBloc began as a final project for <a href="http://www.launchacademy.com/">Launch Academy</a>, a Ruby on Rails bootcamp based in Boston. It will expand as I grow as a developer.
    </div>
    <div class="about-info section-label">
      About WeatherBloc
    </div>
    <div class="about-info">
      <p>
        WeatherBloc is an impromptu meet-up site for neighbors stuck at home during bad weather.
      </p>
      <p>
        The idea for WeatherBloc started after wondering how far I might be willing to walk in a downpour for entertainment. Three blocks for a movie night? One and a half blocks for a free donut? I found the The caviats of this scenario are I became very engaged in the caveats of this scenario, realized there aren’t any apps for this problem, and decided to make it myself.
      </p>
      <p>
        WeatherBloc was initially created as a breakable toy for my final project at Launch Academy. It is a work in progress and will continue to be improved.
      </p>
  </div><br/>
  <div class="about-details">
    <%= link_to 'Back', root_path %>
  </div>
</div>

app/views/welcomes/faqs.html.erb
<h1> FAQs </h1>
<div>
  <p>
    Updated soon!
  </p><br/><br/>

  <%= link_to 'Back', root_path %>
</div><br/>

app/views/welcomes/index.html.erb
<div class="welcome-page">
  <h1>WeatherBloc</h1>

  <%= form_tag events_path, :method => 'get', class: 'welcome-form' do %>
    <p>
      <%= text_field_tag :search, params[:search], id: 'search_field', placeholder: 'Submit your address', class: 'welcome-form-field' %>
      <%= submit_tag "Search for nearby events", id: 'submit-button', class: 'btn btn-default welcome-form-button' %>
    </p>
  <% end %>
</div>